spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/orders/**

        - id: auth-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/auths/**

        - id: notification-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/notifications/**

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
