spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9001

        - id: order-service
          uri: http://localhost:9002



server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
